playground4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

from playground4.web.views import custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('playground4.web.urls')),
]

handler404 = 'playground4.web.views.custom_404_view'

playground4/web/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator
from django.db import models
from django.conf import settings
from django.db.models import Avg
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify


class User(AbstractUser):
    SPORT_CHOICES = [
        ('Basketball', 'Basketball'),
        ('Football', 'Football'),
        ('Volleyball', 'Volleyball'),
        ('Tennis', 'Tennis'),
    ]

    username = models.CharField(validators=[MinLengthValidator(3)], max_length=150, unique=True, verbose_name='username')
    email = models.EmailField(unique=True, verbose_name='email')
    field_owner = models.BooleanField(default=False)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    age = models.PositiveIntegerField(blank=True, null=True)
    image_url=models.URLField(blank=True)
    company_name = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    preferred_sport = models.CharField(max_length=100, choices=SPORT_CHOICES, blank=True)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username


class Field(models.Model):
    DAY_CHOICES = [
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
        (7, 'Sunday'),
    ]
    SPORT_CHOICES = [
        ('Basketball', 'Basketball'),
        ('Football', 'Football'),
        ('Volleyball', 'Volleyball'),
        ('Tennis', 'Tennis'),
    ]

    field_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    sport = models.CharField(max_length=100, choices=SPORT_CHOICES)
    description = models.TextField()
    image_url = models.URLField(blank=True)
    price_per_hour=models.PositiveIntegerField(blank=False, default=0)

    # Start working day of the week (choices: 1-7, representing Monday-Sunday)
    start_working_day = models.IntegerField(choices=DAY_CHOICES, default=1)

    # Start working hour (choices: 16-21)
    start_working_hour = models.IntegerField(choices=[(hour, hour) for hour in range(16, 22)], default=16)

    # End working day of the week (choices: 1-7, representing Monday-Sunday)
    end_working_day = models.IntegerField(choices=DAY_CHOICES, default=1)

    # End working hour (choices: 16-21)
    end_working_hour = models.IntegerField(choices=[(hour, hour) for hour in range(16, 22)], default=16)

    def get_start_working_day(self):
        return dict(self.DAY_CHOICES)[self.start_working_day]

    def get_end_working_day(self):
        return dict(self.DAY_CHOICES)[self.end_working_day]

    def get_start_working_hour(self):
        return f"{self.start_working_hour}:00"

    def get_end_working_hour(self):
        return f"{self.end_working_hour}:00"

    def get_average_rating(self):
        average_rating = self.review_set.aggregate(Avg('rating'))['rating__avg']
        if average_rating:
            return round(average_rating, 1)
        return None

    def __str__(self):
        return self.name

class Reservation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    reservation_date = models.DateField()
    reservation_hour = models.IntegerField(choices=[(hour, f'{hour}:00') for hour in range(16, 22)])

    def __str__(self):
        return f"Reservation for {self.field.name} by {self.user.username}"


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review for {self.field.name} by {self.user.username}"



class Event(models.Model):
    SPORT_CHOICES = [
        ('Basketball', 'Basketball'),
        ('Football', 'Football'),
        ('Volleyball', 'Volleyball'),
        ('Tennis', 'Tennis'),
    ]
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_published = models.DateTimeField(auto_now_add=True)
    field = models.ForeignKey(Field, on_delete=models.CASCADE, blank=True, null=True)
    image = models.URLField(blank=True, null=True)
    sport = models.CharField(max_length=100, choices=SPORT_CHOICES)
    entry_fee=models.PositiveIntegerField(blank=False, default=0)
    event_date = models.DateTimeField(blank=False, default=timezone.now)
    slug = models.SlugField(unique=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('event_detail', kwargs={'slug': self.slug})

    max_sign_ups = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title

class UserEventRegistration(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    registration_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.event.title}"

templates/events/add_event.html
{% extends 'base.html' %}

{% block content %}
    <main class="main-af">
        <article class="add-field">
              <h1>Add Event for {{ field.name }}</h1>

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="field-btn" type="submit">Add Event</button>
                </form>
            <a  href="{% url 'field_detail' pk=field.pk %}">Back to Field</a>
        </article>
    </main>
{% endblock %}

templates/events/all_events_list.html
{% extends 'base.html' %}

{% block content %}
    <main class="main-fd">
        <article class="art">
            <h1 class="all-events-tittle">All Events</h1>

            {% if events_list %}
                <ul>
                    {% for event in events_list %}
                        <li>
                            <h2>{{ event.title }}</h2>
                            <h3>Event date: {{ event.event_date }}</h3>
                            <h3>Field: <a id="link-field" href="{% url 'field_detail' event.field.pk %}">{{ event.field.name }}</a></h3>


                            <div class="news-container">
                                {% if event.image %}
                                    <img class="news-pic" src="{{ event.image }}" alt="Event Image">
                                {% endif %}
                                <p class="news-content">{{ event.content }}</p>
                                <p>Location: {{ event.field.location }}</p>
                                <p>Sport: {{ event.sport }}</p>
                                <p class="news-pub">Published on: {{ event.date_published }}</p>
                                {% if user.is_authenticated %}
                                <button class="field-btn">
                                    <a class="field-btn" href="{% url 'event_detail' event.pk %}">Event Detail</a>
                                </button>
                                {% else %}
                                    <button class="field-btn">
                                        <a class="field-btn" href="{% url 'login' %}?next={{ request.path }}">Please login to see the event</a>
                                    </button>
                                {% endif %}

                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No events available.</p>
            {% endif %}
        </article>
    </main>

{% endblock %}

templates/events/event_detail.html
{% extends 'base.html' %}

{% block content %}
    <main class="main-fd">
        <article class="art">
              <h1>{{ event.title }}</h1>
                <h3>Event date: {{ event.event_date }}</h3>
              <img id="event-pic" src="{{ event.image }}" alt="">
              <p id="event-content">{{ event.content }}</p>
              <p id="event-content">Entry fee: ${{ event.entry_fee }}</p>
              <p id="event-sport">Sport: {{ event.get_sport_display }}</p>
                <p class="news-pub">Published on: {{ event.date_published }}</p>

            {% if user.field_owner %}
                {% if request.user == event.field.field_owner %}
                    <a href="{% url 'registered_users_list' event.pk %}">View Registered Users</a>
                {% endif %}
            {% else %}
                  {% if not is_registered %}
                    <form method="post">
                      {% csrf_token %}
                      <button class="field-btn" type="submit">Sign Up</button>
                    </form>
                  {% else %}
                    <p>You are already registered for this event.</p>
                  {% endif %}
            {% endif %}
        </article>
    </main>

{% endblock %}

templates/events/events_list.html
{% extends 'base.html' %}

{% block content %}
    <main class="main-fd">
        <div class="art">
       <h1>Events for {{ field.name }}</h1>

        {% if events_list %}
            <ul>
                {% for event in events_list %}
                    <li>
                        <h2>{{ event.title }}</h2>
                        <h3>Event date: {{ event.event_date }}</h3>
                        <div class="news-container">
                            {% if event.image %}
                                <img class="news-pic" src="{{ event.image }}" alt="Event Image">
                            {% endif %}
                            <p class="news-content">{{ event.content }}</p>
                            <p class="news-pub">Published on: {{ event.date_published }}</p>
                            {% if user.is_authenticated %}
                                <button class="field-btn">
                                    <a class="field-btn" href="{% url 'event_detail' event.pk %}">Event Detail</a>
                                </button>
                                {% else %}
                                    <button class="field-btn">
                                        <a class="field-btn" href="{% url 'login' %}?next={{ request.path }}">Please login to see the event</a>
                                    </button>
                                {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No events available for this field.</p>
        {% endif %}

            <a href="{% url 'field_detail' pk=field.pk %}">Back to Field</a>
        </div>
    </main>
{% endblock %}

templates/events/registered_users_list.html
{% extends 'base.html' %}

{% block content %}
    <main class="main-fd">
        <article class="art">
              <h1>Registered Users for {{ event.title }}</h1>

              <ol>
                {% for user_registration in registered_users %}
                  <li>
                      <p class="com">{{ user_registration.user.username }}</p>
                        <p class="created">{{ user_registration.registration_date }}</p>
                  </li>

                {% endfor %}
              </ol>
        </article>
    </main>
{% endblock %}